<!DOCTYPE html>
<html>
 <head>
     <meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="formulaire.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Formulaire</title>
 </head>   
 <body>
     <form action="index.php" method="POST">
<div class="header-full">
    <div style="background:#5E0A0A;"></div>
    <div class="gen-flex1">
      <article>
          <?php require './info.phtml'; ?>
          <?php require './langues.phtml'; ?>
          <?php require './fram.phtml'; ?>
          </body>