<h3>Frameworks et Librairies</h3>
<ul>
  <input type="checkbox"> Sass <br>
         <input type="checkbox"> Bootstrap <br>
         <input type="checkbox"> Symfony  <br>
         <input type="checkbox"> Laravel  <br>
</ul>
<h3>Logiciels</h3>
<ul>
  <input type="checkbox"> Photoshop <br>
         <input type="checkbox"> Illustrator <br>
         <input type="checkbox"> XD  <br>
         <input type="checkbox"> Figma  <br>
</ul>
<h3>Couleur du cv</h3>
<label for="color-select">Couleur</label><br>
<select name="couleurs" id="color-select">
    <option value="Bleu">Bleu</option>
    <option value="Rouge">Rouge</option>
</select>

</article>
    </div>
     <input type="submit" value="Envoyer" />
    </form>