<h4>
                        Langues
                    </h4>
                    <fieldset>
                        <input type="checkbox" name="language[]" id="fr" value="Français"/>
                        <label for="fr">Français</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="language[]" id="en" value="Anglais"/>
                        <label for="en">Anglais</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="language[]" id="arabe" value="Arabe"/>
                        <label for="arabe">Arabe</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="language[]" id="breton" value="Breton"/>
                        <label for="breton">Breton</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="language[]" id="espagnol" value="Espagnol"/>
                        <label for="espagnol">Espagnol</label>
                    </fieldset>
                </section>
                <section>
                    <h3>
                        Compétences
                    </h3>
                    <h4>
                        Langages de Programmation
                    </h4>
                    <fieldset>
                        <input type="checkbox" name="lang[]" id="html" value="HTML"/>
                        <label for="html">HTML</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="lang[]" id="css" value="CSS"/>
                        <label for="css">CSS</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="lang[]" id="js" value="JavaScript"/>
                        <label for="js">JavaScript</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="lang[]" id="php" value="PHP"/>
                        <label for="php">PHP</label>
                    </fieldset>
                    <fieldset>
                        <input type="checkbox" name="lang[]" id="sql" value="SQL"/>
                        <label for="sql">SQL</label>
                    </fieldset>